# source: https://github.com/reverbdotcom/.github/blob/main/workflow-templates/conductor.yaml
#   Generates a workflow using conductor - triggers a deploy on demand.
#   This workflow will go away in the future, favoring orchestra sandbox. ( ask #dev-platform )
#
# ---
# How to use this template:
#
# 1. omit from 'options', branches that the repo does not support.
#
#     - lab
#     - infra
#     - preprod
#     - qa
#     - sandbox
#
# 2. remove this "how to" comment
# 3. commit as a PR
# 4. once merged to main, a new workflow will be generated for the repo.


run-name: "${{ inputs.env }} | ${{ github.sha }}"

on:
  workflow_dispatch:
    inputs:
      env:
        required: true
        type: choice
        options:
          - lab
          - infra
          - preprod
          - qa
          - sandbox

jobs:
  conductor:
    uses: reverbdotcom/conductor/.github/workflows/conductor.yaml@main
    with:
      env: ${{ inputs.env }}
