# source: https://github.com/reverbdotcom/.github/blob/main/workflow-templates/conductor-container-image.yaml
# Generates a workflow using conductor - triggers continuous delivery on merge to main.
#
# ---
# How to use this template:
#
# 1. update where the 'main' branch should deploy to, defaults to infra.
# 2. remove this "how to" comment
# 3. commit as a PR
# 4. once merged to main, a new workflow will be generated for the repo.

name: ".1 conductor on main"
run-name: "infra | ${{ github.sha }}"

on:
  push:
    branches:
      - "main"

jobs:
  conductor:
    uses: reverbdotcom/conductor/.github/workflows/conductor-container-image.yaml@main
    secrets: inherit
    with:
      env: infra
