# source: https://github.com/reverbdotcom/.github/blob/main/workflow-templates/conductor-on-main.yaml
# generates a workflow using conductor - triggers continuous delivery on merge to main.

name: "conductor [ $default-branch ]"
run-name: "<changeme: infra|production> | ${{ github.sha }}"

on:
  push:
    branches:
      - $default-branch

jobs:
  delivery:
    uses: reverbdotcom/conductor/.github/workflows/conductor.yaml@main
    with:
      env: <changeme: infra|production>
