# source: https://github.com/reverbdotcom/.github/blob/main/workflow-templates/conductor-on-main.yaml
# Generates a workflow using conductor - triggers continuous delivery on merge to main.
#
# ---
# How to use this template:
#
# 1. update where the 'main' branch should deploy to, defaults to production.
# 2. ( optional ) if your chart name differs from your repo name, override with field `appName: <chart name>`.
# 3. remove this "how to" comment
# 4. commit as a PR
# 5. once merged to main, a new workflow will be generated for the repo.

name: ".1 conductor on main"
run-name: "production | ${{ github.sha }}"

on:
  push:
    branches:
      - "main"

jobs:
  conductor:
    uses: reverbdotcom/conductor/.github/workflows/conductor.yaml@main
    secrets: inherit
    with:
      env: production
      notify: true
      automate_irp: true
