# source: https://github.com/reverbdotcom/.github/blob/main/workflow-templates/conductor-on-main.yaml
# Generates a workflow using conductor - triggers continuous delivery to sandbox on merge to an orchestra branch.
#
# ---
# How to use this template:
#
# 1. ( optional ) if your chart name differs from your repo name, override with field `appName: <chart name>`.
# 2. remove this "how to" comment
# 3. commit as a PR
# 4. once merged to main, a new workflow will be generated for the repo.

name: ".1 conductor on orchestra"
run-name: "${{ github.ref_name }} | ${{ github.sha }}"

on:
  push:
    branches:
      - "sandbox-*"

jobs:
  conductor:
    uses: reverbdotcom/conductor/.github/workflows/conductor-orchestra.yaml@main
    secrets: inherit
