# source: https://github.com/reverbdotcom/.github/blob/main/workflow-templates/conductor-on-main.yaml
# Generates a workflow using conductor - triggers continuous delivery to sandbox on merge to an orchestra branch.
#
# ---
# How to use this template:
#
# 1. remove this "how to" comment
# 2. commit as a PR
# 3. once merged to main, a new workflow will be generated for the repo.

run-name: "${{ github.ref_name }} | ${{ github.sha }}"

on:
  push:
    branches:
      - "sandbox-*"

jobs:
  conductor:
    uses: reverbdotcom/conductor/.github/workflows/conductor-orchestra.yaml@main
    secrets: inherit
